### ISSUE TITLE
"Show only resolved issues" option on Issues Tab doesn't work

### ISSUE THREAD

**Issue by madnut-ua** [jozefizso/teamcity-fogbugz#1]
Hi,
Actually, I don't know what to add else :)
The list shows the same amount of issues ignoring the checkbox state
TeamCity 9.1.5
Let me know, if you need more specific info.

**Comment by jozefizso** [comment]
The plugin correctly loads case status from FogBugz. When I change the view to show resolved issues only, it does correctly filter the data.

![screenshot_012916_011805_pm](https://cloud.githubusercontent.com/assets/287778/12675460/bc26f350-c68a-11e5-955e-e6b350b40130.jpg)

**Comment by madnut-ua** [comment]
Nope, it doesn't...
