### ISSUE TITLE
Default Page Url

### ISSUE THREAD

**Issue by emgrig** [jozefizso/teamcity-fogbugz#2]
Hi Jozef,

I wanted to thank you for this plugin. I was able to use FogBuz as an Issue Tracker for my TeamCity.
Just a two minor changes need it. 
For now the FogBudz default page url is need to be changed from "default.asp" to "f/cases/" in FogbugzConstants.java file. And appendTrailingSlash(string host) function return needs to exclude a white space. URL should looks like something 'https://MyCompany.fogbugz.com/f/cases/'
One more thing I'd really like to have this issue data in my notifications template(common.ftl), but not sure how to modified or create a new #macro with in the fetched issue data.
What's the right namespace or class for that ?
Any help I'll appreciate.

Thanks,
Emil

**Comment by jozefizso** [comment]
I tried the plugin with FogBugz On Demand. The URL in form `https://company.fogbugz.com/default.asp?12345` is working well - user will be redirected to the `https://company.fogbugz.com/f/cases/12345` address by FogBugz automatically.

There is no need to change the plugin code.
